version: '3'
services:
  musketeers:
    image: flemay/musketeers
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app
  alpine:
    image: alpine
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app
  envvars:
    image: flemay/envvars:latest
    env_file: .env
    working_dir: /work
    volumes:
      - .:/work